### ISSUE TITLE
Add how to access to CMIP and Observational data from ETHZ to setup.md

### ISSUE THREAD

**Issue by SarahAlidoost** [ESMValGroup/ESMValTool_Tutorial#101]
The section **Access to CMIP and Observational data and a suitable compute cluster** needs to be updated.

**Comment by JaroCamphuijsen** [comment]
Related to this is PR #100 where the download link is now inside the lesson. Also for episode 5 we need some data for which we should specify a download command to make the setup of this tutorial easier. We also need:

**How to write a recipe with multiple preprocessors;**
- dataset: HadGEM2-ES, project: CMIP5, exp: historical, mip: Omon, ensemble: r1i1p1, start_year: 1859, end_year: 2005 (var: thetoa & thetoaga)

----------------

The following datasets are used in examples, so not necessary to complete exercises

**Adding different datasets for different variables:**
- dataset: UKESM1-0-LL, project: CMIP6, exp: historical,
     ensemble: r1i1p1f2 (solutions mention var: tas &pr)
- {dataset: GPCP-SG, project: obs4mips, level: L3,
             version: v2.2, tier: 1}
- {dataset: HadCRUT4, project: OBS, type: ground,
             version: 1, tier: 2}

**Creating variable groups:**
 - {dataset: CanESM2, ensemble: "r(1:4)i1p1", project: CMIP5}
 - {dataset: MPI-ESM-LR, ensemble: "r(1:2)i1p1", project: CMIP5}
 - {dataset: UKESM1-0-LL, ensemble: "r(1:4)i1p1f2", grid: gn, project: CMIP6}
 - {dataset: CanESM5, ensemble: "r(1:4)i1p2f1", grid: gn, project: CMIP6}
