### ISSUE TITLE
Restructure setup.md, move specific data finding cases to separate pages

### ISSUE THREAD

**Issue by JaroCamphuijsen** [ESMValGroup/ESMValTool_Tutorial#103]
The setup.md page is now very lengthy and includes a lot of system specific guidelines for different clusters. setup.md should be as short and accessible as possible and system specific cases should be easily findable.

Suggestion is to make separate pages for finding data on the different systems (jasmin, dkrz, own machine) and just add a list of links to these pages to setup.md. In this way people can easily navigate to their own case.

**Comment by Peter9192** [comment]
In https://github.com/ESMValGroup/ESMValCore/pull/785 we're proposing a new approach to easily configure ESMValTool for use on specific sites. It might be good to keep an eye on that one.
