### ISSUE TITLE
Wrong time estimation for exercise in episode 2- installation

### ISSUE THREAD

**Issue by SarahAlidoost** [ESMValGroup/ESMValTool_Tutorial#129]
[episode 2-installation ](https://esmvalgroup.github.io/ESMValTool_Tutorial/02-installation/index.html) has one small exercise but the time estimate is 20 min.

**Comment by sverhoeven** [comment]
Agree, exercise is not that hard, but installation might take long time for some people. So a total 20 minutes should be OK for the whole episode.
