### ISSUE TITLE
Reduce number od data needed for episodes 04 and 05

### ISSUE THREAD

**Issue by SarahAlidoost** [ESMValGroup/ESMValTool_Tutorial#132]
Episodes 04 and 05 use a lot of data. This causes a problem when users should download the data. To address the problem, we can minimize the amount of data by skipping some datasets/ensembles, variables and time periods.

**Comment by sverhoeven** [comment]
Sizes might help you pick which datasets to drop
```
17M	pr_GPCP-SG_L3_v2.2_197901-201312.nc
59M	tas_Amon_CanESM2_historical_r1i1p1_185001-200512.nc
59M	tas_Amon_CanESM2_historical_r2i1p1_185001-200512.nc
59M	tas_Amon_CanESM2_historical_r3i1p1_185001-200512.nc
59M	tas_Amon_CanESM2_historical_r4i1p1_185001-200512.nc
51M	tas_Amon_CanESM5_historical_r1i1p2f1_gn_185001-201412.nc
51M	tas_Amon_CanESM5_historical_r2i1p2f1_gn_185001-201412.nc
51M	tas_Amon_CanESM5_historical_r3i1p2f1_gn_185001-201412.nc
51M	tas_Amon_CanESM5_historical_r4i1p2f1_gn_185001-201412.nc
187M	tas_Amon_HadGEM2-AO_historical_r1i1p1_186001-200512.nc
32M	tas_Amon_HadGEM2-ES_historical_r1i1p1_188412-190911.nc
32M	tas_Amon_HadGEM2-ES_historical_r1i1p1_190912-193411.nc
32M	tas_Amon_HadGEM2-ES_historical_r1i1p1_193412-195911.nc
32M	tas_Amon_HadGEM2-ES_historical_r1i1p1_195912-198411.nc
27M	tas_Amon_HadGEM2-ES_historical_r1i1p1_198412-200511.nc
132M	tas_Amon_MPI-ESM-LR_historical_r1i1p1_185001-200512.nc
132M	tas_Amon_MPI-ESM-LR_historical_r2i1p1_185001-200512.nc
46M	tas_Amon_UKESM1-0-LL_historical_r1i1p1f2_gn_195001-201412.nc
46M	tas_Amon_UKESM1-0-LL_historical_r2i1p1f2_gn_195001-201412.nc
46M	tas_Amon_UKESM1-0-LL_historical_r3i1p1f2_gn_195001-201412.nc
46M	tas_Amon_UKESM1-0-LL_historical_r4i1p1f2_gn_195001-201412.nc
56K	thetaoga_Omon_HadGEM2-ES_historical_r1i1p1_185912-200512.nc
867M	thetao_Omon_HadGEM2-ES_historical_r1i1p1_199912-200512.nc
6,5G	thetao_Omon_UKESM1-0-LL_historical_r1i1p1f2_gn_195001-199912.nc
2,0G	thetao_Omon_UKESM1-0-LL_historical_r1i1p1f2_gn_200001-201412.nc
520M	tos_Omon_HadGEM2-AO_historical_r1i1p1_186001-200512.nc
357M	tos_Omon_HadGEM2-CC_historical_r1i1p1_185912-195911.nc
164M	tos_Omon_HadGEM2-CC_historical_r1i1p1_195912-200511.nc
357M	tos_Omon_HadGEM2-ES_historical_r1i1p1_185912-195911.nc
165M	tos_Omon_HadGEM2-ES_historical_r1i1p1_195912-200512.nc
32M	ts_Amon_HadGEM2-ES_historical_r1i1p1_188412-190911.nc
32M	ts_Amon_HadGEM2-ES_historical_r1i1p1_190912-193411.nc
32M	ts_Amon_HadGEM2-ES_historical_r1i1p1_193412-195911.nc
32M	ts_Amon_HadGEM2-ES_historical_r1i1p1_195912-198411.nc
27M	ts_Amon_HadGEM2-ES_historical_r1i1p1_198412-200511.nc

```

**Comment by SarahAlidoost** [comment]
> Sizes might help you pick which datasets to drop
> 
> ```
> 17M	pr_GPCP-SG_L3_v2.2_197901-201312.nc
> 59M	tas_Amon_CanESM2_historical_r1i1p1_185001-200512.nc
> 59M	tas_Amon_CanESM2_historical_r2i1p1_185001-200512.nc
> 59M	tas_Amon_CanESM2_historical_r3i1p1_185001-200512.nc
> 59M	tas_Amon_CanESM2_historical_r4i1p1_185001-200512.nc
> 51M	tas_Amon_CanESM5_historical_r1i1p2f1_gn_185001-201412.nc
> 51M	tas_Amon_CanESM5_historical_r2i1p2f1_gn_185001-201412.nc
> 51M	tas_Amon_CanESM5_historical_r3i1p2f1_gn_185001-201412.nc
> 51M	tas_Amon_CanESM5_historical_r4i1p2f1_gn_185001-201412.nc
> 187M	tas_Amon_HadGEM2-AO_historical_r1i1p1_186001-200512.nc
> 32M	tas_Amon_HadGEM2-ES_historical_r1i1p1_188412-190911.nc
> 32M	tas_Amon_HadGEM2-ES_historical_r1i1p1_190912-193411.nc
> 32M	tas_Amon_HadGEM2-ES_historical_r1i1p1_193412-195911.nc
> 32M	tas_Amon_HadGEM2-ES_historical_r1i1p1_195912-198411.nc
> 27M	tas_Amon_HadGEM2-ES_historical_r1i1p1_198412-200511.nc
> 132M	tas_Amon_MPI-ESM-LR_historical_r1i1p1_185001-200512.nc
> 132M	tas_Amon_MPI-ESM-LR_historical_r2i1p1_185001-200512.nc
> 46M	tas_Amon_UKESM1-0-LL_historical_r1i1p1f2_gn_195001-201412.nc
> 46M	tas_Amon_UKESM1-0-LL_historical_r2i1p1f2_gn_195001-201412.nc
> 46M	tas_Amon_UKESM1-0-LL_historical_r3i1p1f2_gn_195001-201412.nc
> 46M	tas_Amon_UKESM1-0-LL_historical_r4i1p1f2_gn_195001-201412.nc
> 56K	thetaoga_Omon_HadGEM2-ES_historical_r1i1p1_185912-200512.nc
> 867M	thetao_Omon_HadGEM2-ES_historical_r1i1p1_199912-200512.nc
> 6,5G	thetao_Omon_UKESM1-0-LL_historical_r1i1p1f2_gn_195001-199912.nc
> 2,0G	thetao_Omon_UKESM1-0-LL_historical_r1i1p1f2_gn_200001-201412.nc
> 520M	tos_Omon_HadGEM2-AO_historical_r1i1p1_186001-200512.nc
> 357M	tos_Omon_HadGEM2-CC_historical_r1i1p1_185912-195911.nc
> 164M	tos_Omon_HadGEM2-CC_historical_r1i1p1_195912-200511.nc
> 357M	tos_Omon_HadGEM2-ES_historical_r1i1p1_185912-195911.nc
> 165M	tos_Omon_HadGEM2-ES_historical_r1i1p1_195912-200512.nc
> 32M	ts_Amon_HadGEM2-ES_historical_r1i1p1_188412-190911.nc
> 32M	ts_Amon_HadGEM2-ES_historical_r1i1p1_190912-193411.nc
> 32M	ts_Amon_HadGEM2-ES_historical_r1i1p1_193412-195911.nc
> 32M	ts_Amon_HadGEM2-ES_historical_r1i1p1_195912-198411.nc
> 27M	ts_Amon_HadGEM2-ES_historical_r1i1p1_198412-200511.nc
> ```

Great, thank you.

**Comment by SarahAlidoost** [comment]
Only CMIP5 data instructions and settings are considered in the setup and configuration pages. Therefore, I removed examples using CMIP6 data in episode 5. Also, the number of ensembles, and time ranges are limited. Now data size is reduced to 1.6 Gb.
