### ISSUE TITLE
Data download thetaoga

### ISSUE THREAD

**Issue by goord** [ESMValGroup/ESMValTool_Tutorial#137]
- when I follow the tutorial instructions and filter my search to the variable ``thetaoga``, I get results containing salinity, velocities etc. This is very confusing, even though the tutorial says to download only the ``thetaoga`` file.
- After going through the confusing web GUI we are asked to perform a wget command that not only downloads observations but also other CMIP5 model datasets, so what is the point of step 1?

**Comment by Peter9192** [comment]
I totally agree. Also noticed that when I was preparing this. Maybe we can replace the step1 with a link to a good research about data access and esgf.

**Comment by SarahAlidoost** [comment]
@goord Thank you for the feedback. The first part helps users find a` single data file` on a esgf node. We also prepared a `dataset.urls` file to download all of the data needed in the tutorial.
So please follow the command line using `wget` to download the data and then the next command line to change some directory.

@Peter9192 I agree. As a fix to this section, the instruction on `downloading a single file` should be replaced with a link and then moved to the part `For more information see` on this page.
