### ISSUE TITLE
Use asciinema for bash sessions?

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValTool_Tutorial#140]
It might be nice to use https://asciinema.org/ to record the bash sessions, e.g. for the installation procedure. This would be much nicer than having to copy the commands from a shared word document.

**Comment by Peter9192** [comment]
I had a quick look, but it seems this only features pre-recorded coding session, not live, does it? 
If we're preparing additional course material anyway, I'd rather just share a presentation. Yesterday I saw a nice example using [slides](https://slides.com)

**Comment by LisaBock** [comment]
Is now treated in issue #291  and PR #292
