### ISSUE TITLE
Improve the output of recipe_example.yml

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValTool_Tutorial#141]
It would be nice to improve

- The filenames of the output plots, are very lengthy and contain too many underscores
    ```
    diag_CMIP5_HadGEM2-ES_Omon_historical_r1i1p1_thetaoga_prep_timeseries_diag_timeseries_temperature_1900_2000_timeseries_0.pn
    MultipleModels__thetaoga_prep_timeseries_diag_timeseries_temperature_1900_2000_timeseries_.png
    ```
- save the data of the plots also in `work_dir`
- enable provenance/data citation
- use CMIP6 data so the content is more up to date and data citation works better
- add a proper reference to the paper instead of `# Some plots also appear in ESMValTool paper 2.`

**Comment by bouweandela** [comment]
Maybe we could use the example python recipe and diagnostic as a basis for making this nicer. I added some improvements to that too, see here: https://github.com/ESMValGroup/ESMValTool/pull/1827. Those could be included in the next ESMValTool release, scheduled for October.

**Comment by Peter9192** [comment]
Following https://github.com/ESMValGroup/ESMValTool/pull/1827 here are download links for the data in the new example recipe:

```
wget http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/BCC/BCC-ESM1/historical/r1i1p1f1/Amon/tas/gn/v20181214/tas_Amon_BCC-ESM1_historical_r1i1p1f1_gn_185001-201412.nc
wget http://esgf2.dkrz.de/thredds/fileServer/lta_dataroot/cmip5/output1/CCCma/CanESM2/historical/mon/atmos/Amon/r1i1p1/v20120718/tas/tas_Amon_CanESM2_historical_r1i1p1_185001-200512.nc
```
