### ISSUE TITLE
Use esmvaltool.org subdomain?

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValTool_Tutorial#150]
It is possible to host the tutorial with a custom domain name, we could e.g. use https://tutorial.esmvaltool.org?

Any opinion @ESMValGroup/userengagementteam?

**Comment by bouweandela** [comment]
Thanks to @axel-lauer, a link is already available on https://esmvaltool.org, click ESMVALTOOL > Tutorial to go to the link.

**Comment by axel-lauer** [comment]
I would also prefer tutorial.esmvaltool.org because it would be consistent with docs.esmvaltool.org used for the user guide.

**Comment by zklaus** [comment]
@rswamina, pretty much what @axel-lauer said. As I understand it, being consistent here is a better user experience and technically easier.

**Comment by remi-kazeroni** [comment]
The subdomain tutorial.esmvaltool.org/ is now available and points to the tutorial as we discussed earlier. Note that the previous (and default) GitHub domain name https://esmvalgroup.github.io/ESMValTool_Tutorial still works. I'm opening a new issue to discuss if and where we need to update the tutorial address.
