### ISSUE TITLE
Data and Statistics on Tutorial sessions

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValTool_Tutorial#152]
Starting this to discuss the best way to record ESMValTool tutorial sessions and associated information. 

For starters, we have to include date of session, who was involved from the team, venue if relevant, participants details (institute/country/student or researcher etc.) and number of participants.

Additionally it will be good to have a standard feedback form to collect feedback on the tutorials.

**Comment by Peter9192** [comment]
Perhaps we could add 2 sections 'upcoming workshops' and 'past workshops' to the readme of this repo?

**Comment by hb326** [comment]
I had a brief discussion with @axel-lauer this morning, and the idea came up that we could have the basic infomation about held workshops (where was it held, when was it held, held by whom, and how many attended) listed on the ESMValTool webpage:
https://www.esmvaltool.org/

There is already a sub-page that links the tutorial, so we could have that information listed on that sub-page.

**Comment by nielsdrost** [comment]
> I had a brief discussion with @axel-lauer this morning, and the idea came up that we could have the basic infomation about held workshops (where was it held, when was it held, held by whom, and how many attended) listed on the ESMValTool webpage:
> https://www.esmvaltool.org/
> 
> There is already a sub-page that links the tutorial, so we could have that information listed on that sub-page.
The site has the downside of not being editable by the community, so someone at DRL would be tasked with tracking this information. :-(

Perhaps link to it from the site, and keep the info itself in this repo?

**Comment by remi-kazeroni** [comment]
We now have tables listing [presentations](https://github.com/ESMValGroup/Community/blob/main/README.md#presentations) and [trainings](https://github.com/ESMValGroup/Community/blob/main/README.md#training-events) in the [Community](https://github.com/ESMValGroup/Community) repository. These can be update via PRs there.
