### ISSUE TITLE
Edits to episode 2 : Adding information for updating conda package installation

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValTool_Tutorial#160]
It seems like there should be a way for users to update their conda package installation for ESMValTool by grabbing the latest copy of the environment.yml file. It would be helpful to include instructions to do this as part of the installation instructions.

**Comment by SarahAlidoost** [comment]
@rswamina Thank you for the comment. Episode 2 (that is in the basic part of the tutorial) focuses on the installation using conda. The use of the environment.yml file is mentioned only in episode 8 (the advanced part). 

Also, In episode 2, it is mentioned that "If conda is installed, we will see a list of packages. We recommend updating conda before esmvaltool installation. To do so, run:..." Therefore, I assume that the latest packages will be installed.

**Comment by Peter9192** [comment]
Sarah you're right. This is indeed not the same as the environment file. But we do use conda environments. What if the participants already happen to have an installation? You could use

`conda env update -n esmvaltool_tutorial` or something like that, right?

Perhaps we could add a call-out or something like that, to explain that it's usually best to make new, clean environments, but if they really want to upgrade an existing env, they could use this.

**Comment by SarahAlidoost** [comment]
@Peter9192  I found only one command for updating an [environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#updating-an-environment) that uses the yml file. So, if I run `conda env update -n esmvaltool_tutorial` in a terminal, it asks for a yml file.

I am not sure why we need to update the environment using the yml file while we are in the basic part of the tutorial (non-development mode). In the case of an existing installation, I think we can update the package esmvaltool by` conda update esmvaltool `or `conda update esmvaltool-python`. Then conda will update the packages in the environment.  Is this can be a solution?

**Comment by Peter9192** [comment]
> In the case of an existing installation, I think we can update the package esmvaltool by`conda update esmvaltool`or `conda update esmvaltool-python`. Then conda will update the packages in the environment. Can this be a solution?

Yes, that should be enough
