### ISSUE TITLE
Literal tutorial configuration "soft fails" when executing recipe_python in DKRZ

### ISSUE THREAD

**Issue by bsolino** [ESMValGroup/ESMValTool_Tutorial#161]
**Describe the bug**
Following the instructions to the letter in DKRZ results in a very long execution time that is unclear if is normal or an error. I left it run for more than 1h before eventually stopping it manually. More specifically, it was the first execution of a recipe, `esmvaltool run examples/recipe_python.yml` in https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/_episodes/04-recipe.md#running-an-existing-recipe

It seems the root cause is in episode 3, Configuration.
There we are first instructed to uncomment the lines in rootpath for CMIP5 and CMIP6:
https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/_episodes/03-configuration.md#set-the-correct-rootpath

Similarly, we are instructed to uncomment the DRS lines for CMIP5 and obs4mips: https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/_episodes/03-configuration.md#set-the-correct-drs

Note that in both cases the other datasets are explicitly left commented or not configured.

When in the next chapter the `esmvaltool run examples/recipe_python.yml` is run, it gets stuck after this step

```
INFO    [29586] Creating preprocessor 'select_january' task for variable 'tas'
```
looking for a CMIP6 file (from the example output in the tutorial):
```
INFO    [29586] Using input files for variable tas of dataset BCC-ESM1:
/home/user/esmvaltool_tutorial/data/cmip6/tas_Amon_BCC-ESM1_historical_r1i1p1f1_gn_185001-201412.nc
```

Uncommenting all the rootpath and DRS lines solved this issue.

**Comment by Peter9192** [comment]
> Similarly, we are instructed to uncomment the DRS lines for CMIP5 and obs4mips:

It seems I've forgotten to update this one in the recent update. I'll look into that.

Thanks for reporting!
