### ISSUE TITLE
Episode about adding observational datasets to ESMValTool

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValTool_Tutorial#168]
Episode with hands on exercises to include a new data set with ESMValTool - include steps to CMOR-ize as needed.

**Comment by Peter9192** [comment]
@hb326 and I just discussed this issue and came up with the following idea/plan:

- The new episode will be structured more or less as follows
  - Explain (with a figure) what cmorization means, why it is necessary etc.
  - We will make exercises that basically 're-implement' one of the existing cmorizers
  - These exercises will follow the steps from [Contributing a cmorization script](https://docs.esmvaltool.org/en/latest/develop/dataset.html)
  - We want to add better explanation about the different tiers.

- Note that there are currently 2 pages in the documentation that deal with obtaining and cmorizing datasets: 
  1. [Obtaining input data / observations](https://docs.esmvaltool.org/en/latest/input.html#observations)
  2. [Contributing a cmorization script](https://docs.esmvaltool.org/en/latest/develop/dataset.html). Maybe the tutorial can eventually replace this one,  but for now we will leave it in the documentation as well.

**Comment by bouweandela** [comment]
Note that @jvegasbsc has been working on overhauling the way CMORizer scripts work in ESMValGroup/ESMValTool#1657, but I'm not sure how soon this will be ready to merge.

**Comment by jvegasbsc** [comment]
> Note that @jvegasbsc has been working on overhauling the way CMORizer scripts work in ESMValGroup/ESMValTool#1657, but I'm not sure how soon this will be ready to merge.

Probably the ideal time will be just after the release. Changes are huge and we will have more time to fix any issues that may sneak in

**Comment by Peter9192** [comment]
I guess we just update the episode once the PR is merged. The theoretical concepts etc. are still the same, so we'll try to write it such that the structure of the lesson will not have to change substantially.

**Comment by Peter9192** [comment]
So I made this (draft) figure to illustrate everything related to observational dataset support: CMOR-compliant vs non-compliant data, different project IDs, what actually *is* CMORization, and what are *fixes*, etc.

I'd really like to get some feedback on this: do you think it helps, what is good about it and what can be improved, is it factually correct, etc. Thanks in advance!

@hb326 @nielsdrost @SarahAlidoost @rswamina @remi-kazeroni @stefsmeets @bvreede @bsolino 

![ESMValTool data figure](https://user-images.githubusercontent.com/17080502/107387421-16fad080-6af5-11eb-85fd-b8d698613566.png)

*While data downloading is not currently supported, ESMValTool does provide some helpful information. (And yes, hopefully it will be added for a selection of datasets soon in ESMValGroup/ESMValTool#1657).

**Comment by rswamina** [comment]
@Peter9192  - For lack of a better intuition or readily available CMOR-izer, in the "CMORize step" I ended up using ESMValTool's  CMOR check and fixing issues. So that was a feedback process for me going from RAWOBS  to OBS. I don't know if there are CMOR-izers/checkers available to use but at that time this was what worked.

**Comment by jvegasbsc** [comment]
> While data downloading is not currently supported, ESMValTool does provide some helpful information. (And yes, hopefully it will be added for a selection of datasets soon in ESMValGroup/ESMValTool#1657).

In theory, you can download all CMIP5 and CMIP6 data though Synda

**Comment by Peter9192** [comment]
@rswamina thanks, I can really understand that reasoning. I think we will cover that in the episode. The goal of this figure is to illustrate the context for why this is needed. 

@jvegasbsc good point, I can include e.g. another arrow about obtaining cmip data, for now I had been focusing on the obs part.

@hb326 Maybe we can include the Tier system 'in front' of the download arrow?

**Comment by nielsdrost** [comment]
Nice figure @Peter9192! I would add another "download" arrow for CMIP data, and move the legend to either above or underneath the image. At first glance it seems to be part of the figure. I would also recommend having a bit more distinct colors, all the shades of blue are a bit hard to describe during teaching. :-)

Perhaps it is also worth considering putting "native6" in the right column.

**Comment by SarahAlidoost** [comment]
@Peter9192 Thank you, it is great. Just minor comments: 

- I think `run diagnostics scripts` should be replaced by `run recipe scripts` because even when the diagnostics script is None, the user can process the cmorized data.
- Similar to the item `run diagnostics scripts`, the `cmorizer` can be replaced by `run cmorizer scripts`. 
- As this figure is used in the tutorial, it would be good if we can make a distinction between what is done by a user or the tool. For example, now it seems that both `fix known issues` and `cmorizer` are done completely by the tool which is not the case.

**Comment by bvreede** [comment]
Can I just say thank you? As a novice (and a visual learner), this made so many things a whole lot clearer to me.

**Comment by Peter9192** [comment]
Thanks everyone for the feedback. Here's an updated version in which I tried to implement most of it. Let me know if you have any more suggestions.

![ESMValTool data figure](https://user-images.githubusercontent.com/17080502/107638333-b93ec380-6c6f-11eb-8c7d-55b722dd18f5.png)

**Comment by nielsdrost** [comment]
Nice work @Peter9192. Some further comments:

- The "backward" "Or run ESMValtool on ESGF compute node" arrow is really confusing.
- Running on an esgf machine with data already there holds for most download arrows. So this may need to be represented some other way.
- I would leave out the synda arrow for now. Once  ESMValGroup/ESMValTool#1657 is merged all download arrows changes to blue or at least blue/pink :-)
- If you put native6 between obs4mips and OBS you avoid the download arrow crossing rawobs and make the explicit cmorization box the same height as the RAWOBS box.
- I would add arrows from OBS and OBS6 to the CMOR check arrow to show it still travels this direction. Perhaps leave it blank or mark it "load" or something? Computer scientists in me would label it "nop" but that would be mostly confusing to users I think ;-)

**Comment by Peter9192** [comment]
Version 3 @nielsdrost something like this?

![ESMValTool data figure](https://user-images.githubusercontent.com/17080502/108221936-96f9e980-7138-11eb-845a-437f88ba976b.png)

**Comment by hb326** [comment]
Ok, guys. I have finished the last pieces of text for the first draft of the episode. @Peter9192, I think we are ready for comments from people now, right?

**Comment by Peter9192** [comment]
Great work @hb326! I haven't yet had the time to go over the entire episode again, but I had a quick look already. The new sections look absolutely awesome. There's just one small issue with the structure that I think we might want to address before we have other people review it. I left a comment in the PR, but unfortunately I don't have time to work on it right now.

**Comment by hb326** [comment]
> 
> 
> Great work @hb326! I haven't yet had the time to go over the entire episode again, but I had a quick look already. The new sections look absolutely awesome. There's just one small issue with the structure that I think we might want to address before we have other people review it. I left a comment in the PR, but unfortunately I don't have time to work on it right now.

Hey @Peter9192, I will look at your comment on Monday and will work some more on this then. Thanks for checking it briefly today!
