### ISSUE TITLE
ESMValTool Tutorial (Advanced Topics) Marathon Sessions

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValTool_Tutorial#172]
Hi @ESMValGroup/userengagementteam , @valeriupredoi , @bouweandela , @zklaus 

Please indicate your availability for the next ESMValTool Tutorial Marathon Session so we may create new material for advanced topics. An ongoing  list of topics is available here [in the projects page](https://github.com/ESMValGroup/ESMValTool_Tutorial/projects/1). The plan is to allot 3 days to get the bulk of the material finished. Do tag any others you think may be interested in contributing or for reviewing.

[Doodle poll link](https://doodle.com/poll/vdb9pvdxhutf2htc).

Please fill the poll by **Monday, Jan 18th 2020.**
Thanks!

**Comment by bouweandela** [comment]
My availability is extremely limited at the moment, at least until daycares re-open here in the Netherlands. If you let me know what days you planned, I'll try to join when I can.

**Comment by Peter9192** [comment]
@rswamina @SarahAlidoost can someone post an update about the plans for this sprint?

**Comment by SarahAlidoost** [comment]
> @rswamina @SarahAlidoost can someone post an update about the plans for this sprint?

The plan has been sent by Ranjini via email with the subject "**ESMValTool Tutorial marathon in Feb**". In her email, there is a link to a google document where the program can be found. **Note: times are in GMT**. 
Also, the document includes the **MS Team link to join the meeting**. Let us know if you need more information.

**Comment by rswamina** [comment]
> > @rswamina @SarahAlidoost can someone post an update about the plans for this sprint?
> 
> The plan has been sent by Ranjini via email with the subject "**ESMValTool Tutorial marathon in Feb**". In her email, there is a link to a google document where the program can be found. **Note: times are in GMT**.
> Also, the document includes the **MS Team link to join the meeting**. Let us know if you need more information.



> @rswamina @SarahAlidoost can someone post an update about the plans for this sprint?

Thanks, @SarahAlidoost ! I have sent a reminder email as well now. @Peter9192 let me know if you stll don't see it.

**Comment by Peter9192** [comment]
I got the reminder thanks! I was thinking it would be good to have this information here on github as well. Not everyone in my team got the email, but some of them would still like to join (partly). They couldn't find any info and I thought this place would make sense. Just like we usually have an issue about the monthly meetings which states the data and the link to the meeting.

**Comment by SarahAlidoost** [comment]
> I got the reminder thanks! I was thinking it would be good to have this information here on github as well. Not everyone in my team got the email, but some of them would still like to join (partly). They couldn't find any info and I thought this place would make sense. Just like we usually have an issue about the monthly meetings which states the data and the link to the meeting.

Thank you for the suggestion. The main reason was the meeting link that is not password-protected in the case of using MS Team. For sprints in the future, we can share the program and resources in a GitHub issue and send only the meeting link via email. For safety reasons, it is recommended to not share meeting links in public forums if they are not password-protected.
