### ISSUE TITLE
Conda install from environment.yml does not work (on OSX)

### ISSUE THREAD

**Issue by bvreede** [ESMValGroup/ESMValTool_Tutorial#177]
**Describe the bug**
Package gxx_linux-64 cannot be found by conda, when generating the environment to preview the lesson. Environment generation is aborted.

This is likely an OSX issue.

**Comment by SarahAlidoost** [comment]
for more info, see https://carpentries.github.io/lesson-example/setup.html

**Comment by SarahAlidoost** [comment]
Alternatively, [GitPod](https://www.gitpod.io/) provides a cloud-based development environments for projects.

**Comment by bouweandela** [comment]
You can replace the `gxx_linux-64` package by the platform independent `compilers` package, then it should work on both Linux and OSX.
