### ISSUE TITLE
Use of config file in log

### ISSUE THREAD

**Issue by bvreede** [ESMValGroup/ESMValTool_Tutorial#187]
The tutorial explicitly mentions that the default `config-user.yml` file, which is the default config file, should be specified in the logger (see _Investigating the log messages_ in [Running your first recipe](https://esmvalgroup.github.io/ESMValTool_Tutorial/04-recipe/index.html)) However, unless you're specifying the config file on the command line, the logger will state `Using config file None`.

This can be fixed in the tutorial, but may also be something we want to adjust in ESMValCore (see [current reference](https://github.com/ESMValGroup/ESMValCore/blob/master/esmvalcore/_main.py#L383)), so that the default config will be logged.

Opinions?

**Comment by Peter9192** [comment]
Yes, very good point! I prefer the second option: fix it in the core.

**Comment by rswamina** [comment]
@bvreede and @Peter9192 - Assuming I understood this issue correctly, looks like this is resolved. When I run esmvaltool with the default config file (and not specifying a config file in the command line arguments list), the log output specifies the full path of the default config file and is not None. If this is now resolved, can we close this issue?

**Comment by Peter9192** [comment]
Yes. For reference, it was fixed in https://github.com/ESMValGroup/ESMValCore/pull/1233
