### ISSUE TITLE
Order of episodes in the tutorial

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValTool_Tutorial#198]
Is there a need to order the newly added episodes in the tutorial (CMORization and adding a new diagnostic)? Would be useful to get feedback here so we can finalize the content and make it ready for testing.
Requesting input from @ESMValGroup/userengagementteam .

**Comment by Peter9192** [comment]
What about the following order?

1. Introduction
2. Installation
3. Configuration
4. Running your first recipe
5. Development and contribution
6. Writing your own recipe
7. Writing your own diagnostic
8. CMORization: adding new datasets to ESMValTool
9. Debugging
10. Conclusion

Note that an instructor can always make their own selection out of the available lessons, so they could decide to skip 5, for example. But this structure shows that we suggest people learn to work with ESMValTool in this order.

**Comment by rswamina** [comment]
@Peter9192 - I am happy with this. Will go ahead and reorder them since no one else has any further comments.

**Comment by Peter9192** [comment]
Hmm wait a second @rswamina... I think it doesn't work, since episode 5 in my proposal is pointing "back" to episode 6 I think... so we might wanna swap those two.

**Comment by SarahAlidoost** [comment]
> Hmm wait a second @rswamina... I think it doesn't work, since episode 5 in my proposal is pointing "back" to episode 6 I think... so we might wanna swap those two.

I agree, and another reason for this is that users can write and run their won recipes without a development installation.

**Comment by rswamina** [comment]
It seems like the Conclusion is the basic tutorial conclusion, so it should come before the advanced topics as the 5th episode perhaps. We don't have a final conclusion. Most first time users will likely stop here in the first pass so it might be ok to do that. Is that acceptable @SarahAlidoost and @Peter9192 ?
