### ISSUE TITLE
Urls for datasets in Prerequisites does not exist anymore

### ISSUE THREAD

**Issue by antoine1501** [ESMValGroup/ESMValTool_Tutorial#209]
https://github.com/ESMValGroup/ESMValTool_Tutorial/raw/master/data/dataset.urls
Datasets used for running examples/recipe_python.yml in episode 4 is not available (with the path above).
I tried with this urls : https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/main/data/dataset.urls, but it seems not to be the proper datasets either.

**Comment by antoine1501** [comment]
Datasets for esmvaltool_tutorial are located here : https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/main/data/dataset.urls

**Comment by Peter9192** [comment]
Good call! We recently renamed the branch from master to main. I made a PR to change the relevant URLS: #211. @antoine1501 or @rswamina would you be able to review it?
