### ISSUE TITLE
Question about adding a new author and who the author should be

### ISSUE THREAD

**Issue by ehogan** [ESMValGroup/ESMValTool_Tutorial#210]
**How can we help?**

Hello :)

The [Writing your own recipe](https://esmvalgroup.github.io/ESMValTool_Tutorial/06-preprocessor/index.html) lesson contains details on how to add a known author to the new recipe, but no details on how to add a new author.

Based on [this page in the ESMValTool documentation](https://docs.esmvaltool.org/en/latest/community/code_documentation.html#list-of-authors), am I correct in thinking it is simply a case of adding the new author to [esmvaltool/config-references.yml](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/config-references.yml) as part of the PR when adding a new recipe? Or is there a more formal process?

A follow-up question: my colleague and I are converting AutoAssess metrics to ESMValTool metrics; should the author be the original author of the code (even though they may never contribute to ESMValTool), or should it be the person actually writing / adding the code to ESMValTool, i.e. us?

Many thanks!

**Comment by Peter9192** [comment]
Hello and welcome! The answer to your first question is "yes". I'm not entirely sure about the second question, but I'd say you and your colleague are the authors of this recipe, and I would then include a reference to the original code to acknowledge those authors.

**Comment by ehogan** [comment]
Thanks @Peter9192, and apologies for the delay in my reply! We are doing as you suggested :) I was wondering whether it would be worth updating the tutorial to be explicit on how to add a new author? What do you think? I'd be happy to create a PR, if that's helpful?

**Comment by Peter9192** [comment]
That's probably a good idea! Please go ahead with the PR, I'm a bit pressed for time but I'll try to review it once it's ready.
