### ISSUE TITLE
Re-name the repo?

### ISSUE THREAD

**Issue by SarahAlidoost** [ESMValGroup/ESMValTool_Tutorial#22]
The name "tutorial" is not quite descriptive, especially when this repo is forked. It will be good to consider renaming, some names are already suggested in #3 : ESMValTutorial, ESMValTool_Tutorial, ESMValTraining, ... . 
I think that "**ESMValTool_Tutorial**" is fine.

**Comment by Peter9192** [comment]
except for the typo... and what if we make multiple 'tutorial**s**'? Perhaps the term 'training' is a bit wider applicable?

**Comment by ledm** [comment]
I'm not opposed to this idea. I suspect that we will already have several tutorials going. Not sure **Training** is the right word though. I like **Tutorials**.

**Comment by SarahAlidoost** [comment]
@Peter9192 thanks. I agree about multiple tutorials in the future. Actually, each tutorial should be organized in a separate repository. Therefore, this repository contains only one tutorial. I looked over some similar cases for example, how the software carpentry organizes the lessons in github. You can have look at https://github.com/swcarpentry. They use a [meta-repository](https://github.com/swcarpentry/swcarpentry) that helps navigate lessons. We can also make a meta-repository named ESMVal_Training or something else. 
 
I like the `tutorial` because it seems to be a common term to work with a software. However, the name of this repository should be very specific and descriptive. I think a name like ESMValTool_Tutorial is not good enough. 
 
The contributing.md mentions ([under review](https://github.com/ESMValGroup/tutorial/issues/24)) that _“The tutorial is a set of lessons (or episodes) that together teach basic skills needed to work with ESMValTool in climate-related domains.”_
Therefore, I suggest choosing a name like ESMValTool_Tutorial4Beginners or ESMValTool_Tutorial_Beginners. 

I'd like to ask other members of the User engagement team (@rswamina, @hb326, @bouweandela, @ledm ) to suggest ideas as well. Thanks in advance.

**Comment by Peter9192** [comment]
> We can also make a meta-repository named ESMVal_Training or something else.

This makes sense if we'll be hosting multiple tutorials. In that case, I agree that it would make sense to make the name of each individual tutorial a bit more specific. I like both of your suggestions, or perhaps ESMValTool_Tutorial_Basics or ESMValTool_Tutorial_Getting_Started?

**Comment by bouweandela** [comment]
@ESMValGroup/userengagementteam Did you discuss this on the last day of the tutorial and make a decision?

**Comment by BenMGeo** [comment]
I would not use the "beginners" tag, so people do not feel bad comming back if they want to check on it again. I prefer a variation of Peter's suggestion:
ESMValTool_Tutorial_Basics / ESMValTool_Basics_Tutorial (Depending on the planned namespace to add other tutorials).
