### ISSUE TITLE
Path is broken (raw CMIP data)

### ISSUE THREAD

**Issue by LisaBock** [ESMValGroup/ESMValTool_Tutorial#221]
On the page "Preparations for participating in the tutorial" in the section "Using your own machine" is the path to the CMIP file list broken.

**Comment by LisaBock** [comment]
However, the existing path is working for me. @stacristo could you please check again?

**Comment by stacristo** [comment]
It still only downloads a text file containing the message below:

# Dataset urls required fo tutorial, described at https://esmvalgroup.github.io/ESMValTool_Tutorial/setup.html#using-your-own-machine
# For episodes 4 and 5
http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/BCC/BCC-ESM1/historical/r1i1p1f1/Amon/tas/gn/v20181214/tas_Amon_BCC-ESM1_historical_r1i1p1f1_gn_185001-201412.nc
http://esgf3.dkrz.de/thredds/fileServer/lta_dataroot/cmip5/output1/CCCma/CanESM2/historical/mon/atmos/Amon/r1i1p1/v20120718/tas/tas_Amon_CanESM2_historical_r1i1p1_185001-200512.nc

Is this the intended output?

**Comment by LisaBock** [comment]
Will close the issue as it is working now for @stacristo.
