### ISSUE TITLE
Update the data flow figure for the cmorization episode

### ISSUE THREAD

**Issue by remi-kazeroni** [ESMValGroup/ESMValTool_Tutorial#247]
**Is your feature related to a problem? Please describe.**
ESMValTool has now the capability to download ESGF data at runtime and also provides downloading scripts for 75% of the supported datasets. I was wondering if it would be a good idea to update the [figure](https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/main/fig/data_flow.png) at the top of [episode 9](https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/main/_episodes/09-cmorization.md) to indicate that the download can be partly/fully done within ESMValTool, at least for the first and third arrows.

**Would you be able to help out?**
Would you have the time and skills to implement the solution yourself?
Maybe but I'm not sure how this figure was produced and what is the best way to edit it. Could you please advise @Peter9192?

**Comment by Peter9192** [comment]
That figure was made in my favourite tool Microsoft PowerPoint 😎 

Here's the source file (with some previous versions also included):
[ESMValTool data figure.pptx](https://github.com/ESMValGroup/ESMValTool_Tutorial/files/9241648/ESMValTool.data.figure.pptx)

**Comment by remi-kazeroni** [comment]
Thanks @Peter9192 for sharing the source file! I've tried to update the figure in #251. Could you please take a look whenever you have time for that 😃
