### ISSUE TITLE
On push checks failing

### ISSUE THREAD

**Issue by mo-tgeddes** [ESMValGroup/ESMValTool_Tutorial#250]
When I was adding a quick-start guide I noticed that when I pushed, checks would fail, but all the checks were on files I hadn't touched. I'm going to go through and fix the files so that they will pass the checks and actual mistakes will be easier to see.

**Comment by remi-kazeroni** [comment]
Thanks for opening an issue about this. In fact, checks have been failing for quite some time (see all [recently merged PRs](https://github.com/ESMValGroup/ESMValTool_Tutorial/pulls?page=1&q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc) with a ❌). It would be great to improve that but I'm not sure whether all the problems are quick to fix... If not, I think it is still acceptable to merge PRs after reviewer's approval.

**Comment by SarahAlidoost** [comment]
See issue #218
