### ISSUE TITLE
Deleted branch highlight_basic_and_advanced_topics still seen in repo

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValTool_Tutorial#268]
The branch called highlight_basic_and_advanced_topics from a merged PR [243](https://github.com/ESMValGroup/ESMValTool_Tutorial/pull/243) is supposed to be deleted but is still seen in the repo. @SarahAlidoost - could you suggest why this might be and what I should do to get rid of it?

**Comment by SarahAlidoost** [comment]
This might happen if someone presses the "`Restore branch`" button or pushes the local branch again. I think it is not easy to get access to "push log or history" to know what happened. See the list of branches [here](https://github.com/ESMValGroup/ESMValTool_Tutorial/branches) in different categories like **Active**, **Stale**, .... It is possible to delete branches. Please take extra care in deleting others' branches.

**Comment by rswamina** [comment]
I have deleted the branch since it was mine and it was no longer active.
