### ISSUE TITLE
Update instructions on downloading the data before starting the tutorial

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValTool_Tutorial#275]
The tutorial currently describes [here](https://esmvalgroup.github.io/ESMValTool_Tutorial/setup.html) how to download the climate model data before starting the tutorial

> Using your own machine
> ----------------------
>
> Please skip this section if you are not going to use ESMValTool on your local machine and go [here](https://esmvalgroup.github.io/ESMValTool_Tutorial/setup.html#github-account-advanced).
>
> If you are planning on running ESMValTool on your own machine, please make sure that you are able to download CMIP data and that you have several GB of space available to install conda and ESMValTool, but also enough to make a copy of some data (~2Gb).
> 
> To download the data required by this tutorial, run the following command using [wget](https://en.wikipedia.org/wiki/Wget):
>
        wget --no-clobber --input-file \
          https://github.com/ESMValGroup/ESMValTool_Tutorial/raw/main/data/dataset.urls \
          --directory-prefix $HOME/esmvaltool_tutorial/data/

Note that in version 2.8 of the tool, the dataset `CanESM2` has been replaced with `bcc-csm1-1` in [examples/recipe_python.yml](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/examples/recipe_python.yml), so the file [data/dataset.urls](https://github.com/ESMValGroup/ESMValTool_Tutorial/raw/main/data/dataset.urls) will need to be updated. It would be good to add the `areacella` files for the `area_statistics` preprocessor as well. The file would then look like this:
```
http://esgf2.dkrz.de/thredds/fileServer/lta_dataroot/cmip5/output1/BCC/bcc-csm1-1/historical/mon/atmos/Amon/r1i1p1/v1/tas/tas_Amon_bcc-csm1-1_historical_r1i1p1_185001-201212.nc
http://esgf2.dkrz.de/thredds/fileServer/lta_dataroot/cmip5/output1/BCC/bcc-csm1-1/historical/fx/atmos/fx/r0i0p0/v1/areacella/areacella_fx_bcc-csm1-1_historical_r0i0p0.nc
http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/BCC/BCC-ESM1/historical/r1i1p1f1/Amon/tas/gn/v20181214/tas_Amon_BCC-ESM1_historical_r1i1p1f1_gn_185001-201412.nc
http://esgf3.dkrz.de/thredds/fileServer/cmip6/CMIP/BCC/BCC-ESM1/1pctCO2/r1i1p1f1/fx/areacella/gn/v20190613/areacella_fx_BCC-ESM1_1pctCO2_r1i1p1f1_gn.nc
```
The total amount of data is only 124 MB, not 2 GB, so it would be good to update that in the text.

Alternatively, this step could be completely removed from the instructions, as it is much easier to automatically download the required data by running `esmvaltool` than it is to download it using `wget`. That also has the advantage that data is stored in subdirectories, so [new features](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/changelog.html#highlights), such as wildcards and recording the version of the data actually work.

**Comment by rswamina** [comment]
@bouweandela and @SarahAlidoost - This is now fixed in PR #279. Please reopen if needed, I am closing this issue now.
