### ISSUE TITLE
New url for the tutorial

### ISSUE THREAD

**Issue by remi-kazeroni** [ESMValGroup/ESMValTool_Tutorial#281]
The online tutorial is now available via tutorial.esmvaltool.org (see #150). This is a subdomain of esmvaltool.org (just like for the docs on docs.esmvaltool.org). The old address (https://esmvalgroup.github.io/ESMValTool_Tutorial) still works fine so the change is backward compatible.

Question is: do we need to change the tutorial url and where (episodes, readthedocs, github, ...)?

**Comment by SarahAlidoost** [comment]
In the **About** section of this repository, I changed the link from `https://esmvalgroup.github.io/ESMValTool_Tutorial` to `tutorial.esmvaltool.org`. This changes the **Custom domain** in [settings/pages](https://github.com/ESMValGroup/ESMValTool_Tutorial/settings/pages). Now a DNS check is succesful. 

A search on `https://esmvalgroup.github.io/ESMValTool_Tutorial` in esmvalgroup shows where this address is used, see [here](https://github.com/search?q=org%3AESMValGroup%20https%3A%2F%2Fesmvalgroup.github.io%2FESMValTool_Tutorial&type=code). As seen most of them are hyperlink and they are still valid.

**Comment by remi-kazeroni** [comment]
Thanks! For ESMValTool, changes are done in https://github.com/ESMValGroup/ESMValTool/pull/3236. The links are not broken but it's nicer to ensure consistency throughout the project
