### ISSUE TITLE
Command to build documentation is out-of-date

### ISSUE THREAD

**Issue by schlunma** [ESMValGroup/ESMValTool_Tutorial#290]
The command to build the documentation in the episode on _Development and contribution_ is out of date and not working any longer.

Instead of

```bash
python setup.py build_sphinx -Ea
```

it needs to read

```bash
sphinx-build doc/sphinx/source/ doc/sphinx/build/
```

See also https://docs.esmvaltool.org/en/latest/community/code_documentation.html#how-to-build-and-view-the-documentation.

**Comment by LisaBock** [comment]
Solved by PR #286
