### ISSUE TITLE
Mamba error: in  2 ESMValTool dependencies (Development episode)

### ISSUE THREAD

**Issue by gulcing** [ESMValGroup/ESMValTool_Tutorial#321]
Hi all,

While updating the development section, I had problems with the installation section. I installed miniforge but I couldn't run this :

`mamba create --name esmvaltool esmvaltool
`

I got this error:

```
Looking for: ['esmvaltool']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
pkgs/main/osx-arm64                                           No change
pkgs/r/osx-arm64                                              No change
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                              No change
Could not solve for environment specs
The following package could not be installed
└─ esmvaltool is not installable because it requires
   └─ esmvaltool-r [2.10.0 hd8ed1ab_0|2.3.0 hd8ed1ab_1|...|2.9.0 hd8ed1ab_0], which requires
      └─ r-mapproj, which does not exist (perhaps a missing channel).
```

**Comment by gulcing** [comment]
The problem was solved with the installation of esmvaltool-python package.
https://docs.esmvaltool.org/en/latest/quickstart/installation.html#installation-of-subpackages

**Comment by CoquartLaure** [comment]
I could install Miniforge3-MacOSX-x86_64 from https://github.com/conda-forge/miniforge?tab=readme-ov-file#miniforge3 on my MAC Ventura 13.6.7 and then esmvaltool using mamba. I did not test on a recipe.

I also installed Miniforge3-Linux-x86_64 and then esmvaltool on our Linux cluster scylla and I could use it to run a recipe.
