### ISSUE TITLE
Dependabot alert

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValTool_Tutorial#322]
Dear @ESMValGroup/esmvaltool-developmentteam  and @ESMValGroup/userengagementteam ,

I got this error when trying to push changes to the tutorial repository:

```
remote: GitHub found 3 vulnerabilities on ESMValGroup/ESMValTool_Tutorial's default branch (3 moderate). To find out more, visit:
remote:      https://github.com/ESMValGroup/ESMValTool_Tutorial/security/dependabot
remote: 
```
On visiting the website, these were listed as Dependabot alerts. Can someone who understands this, advice on how to deal with this? Thanks!
-Ranjini

**Comment by bouweandela** [comment]
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

**Comment by rswamina** [comment]
> please merge those PRs from the dependabot - those are security updates, if you could post a link here, then I can also have a look at those PRs 🍺

@valeriupredoi - I think these are merged now. How can we fix any issues now?

**Comment by valeriupredoi** [comment]
should be safe, I can do it if you get stuck :beer:

**Comment by rswamina** [comment]
@valeriupredoi  - I am reopening this because it seems I had not put in a valid package in the `dependabot.yml` file. I have put in `bundler` now but not sure how to do this for all packages or if this is correct. The original alert message is [here](https://github.com/ESMValGroup/ESMValTool_Tutorial/security/dependabot) . I noticed the error under Insights->Dependecy Graph
->Dependabot where it said:

```


Dependabot encountered the following error when parsing your .github/dependabot.yml:

The property '#/updates/0/package-ecosystem' value "" did not match one of the following values: npm, bundler, composer, devcontainers, maven, mix, cargo, gradle, nuget, gomod, docker, elm, gitsubmodule, github-actions, pip, terraform, pub, swift

Please update the config file to conform with Dependabot's specification.
```
Can you suggest if I should add any specific packages?
Thanks!
