### ISSUE TITLE
Transfer ownership of this repository to User Engagement Team

### ISSUE THREAD

**Issue by bouweandela** [ESMValGroup/ESMValTool_Tutorial#4]
Once the governance document is agreed on, I think a User Engagement Team group should be made in the ESMValGroup organization and that team should be the owner of this repository.

**Comment by Peter9192** [comment]
@bouweandela there is a team and we do have admin rights for the tutorial repo. Can this be closed?

**Comment by bouweandela** [comment]
The esmvaltool @ESMValGroup/esmvaltool-coreteam also stlil has admin rights. Is that desirable? Or should it be just @ESMValGroup/userengagementteam?

**Comment by Peter9192** [comment]
I thought it makes sense that the core team also has admin rights for this repo. My impression so far is that the user engagement team mostly focuses on the content, whereas the core dev team might want to be able to touch some advanced technical settings if needed.
