### ISSUE TITLE
How to get data on my own machine

### ISSUE THREAD

**Issue by sverhoeven** [ESMValGroup/ESMValTool_Tutorial#54]
The https://esmvalgroup.github.io/tutorial/setup.html (after #46 is merged) shows that if I want to use my own machine then I should be able to download CMIP. However it does not mention how to do that. It seems synda is involved, but there is no description what it does or how to install and configure it.

It would be nice to install synda in this section. Something like instructions at https://docs.esmvaltool.org/en/latest/input.html#models

**Comment by Peter9192** [comment]
Not sure if the set-up page is the right place for that, though. Sounds like a big enough topic for a stand-alone episode on obtaining input data/installing synda

**Comment by sverhoeven** [comment]
True, could be own episode.  I tried to setup synda and was amazed by the number of steps required.

**Comment by bouweandela** [comment]
I think that installing synda might be a bit too much for this tutorial. Just going to an ESGF website and clicking the download button might be easier, e.g. https://esgf-data.dkrz.de/projects/esgf-dkrz/

**Comment by bouweandela** [comment]
We could then mention synda or esgf-python as more advanced alternatives.

**Comment by bouweandela** [comment]
> True, could be own episode. I tried to setup synda and was amazed by the number of steps required.

I would recommend following the instructions [here](
http://prodiguer.github.io/synda/sdt/conda_install.html), it's a conda install and you have to fill in your credentials. The only thing that is not clearly mentioned there is how to get the esgf account needed to answer the credentials questions.

**Comment by JaroCamphuijsen** [comment]
Related to this is PR #100 where the download link is now inside the lesson. Also for episode 5 we need some data for which we should specify a download command to make the setup of this tutorial easier. We also need:

**How to write a recipe with multiple preprocessors;**
- dataset: HadGEM2-ES, project: CMIP5, exp: historical, mip: Omon, ensemble: r1i1p1, start_year: 1859, end_year: 2005 (var: thetoa & thetoaga)

----------------

The following datasets are used in examples, so not necessary to complete exercises

**Adding different datasets for different variables:**
- dataset: UKESM1-0-LL, project: CMIP6, exp: historical,
     ensemble: r1i1p1f2 (solutions mention var: tas &pr)
- {dataset: GPCP-SG, project: obs4mips, level: L3,
             version: v2.2, tier: 1}
- {dataset: HadCRUT4, project: OBS, type: ground,
             version: 1, tier: 2}

**Creating variable groups:**
 - {dataset: CanESM2, ensemble: "r(1:4)i1p1", project: CMIP5}
 - {dataset: MPI-ESM-LR, ensemble: "r(1:2)i1p1", project: CMIP5}
 - {dataset: UKESM1-0-LL, ensemble: "r(1:4)i1p1f2", grid: gn, project: CMIP6}
 - {dataset: CanESM5, ensemble: "r(1:4)i1p2f1", grid: gn, project: CMIP6}

**Comment by JaroCamphuijsen** [comment]
See #103 about restructuring the setup.md to make it more concise and move all system specific instructions on how to find data to separate pages.

**Comment by JaroCamphuijsen** [comment]
Maybe we can add a single wget script (generated from the ESGF datacart?) that downloads all the necessary files?

**Comment by bouweandela** [comment]
Maybe this could be interesting to link somewhere? It's a recorded webinar introducing ESGF and CMIP6

**Comment by sverhoeven** [comment]
In PR #104 I added a wget command list of [dataset.urls ](https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/instructions-data-download-own-machine-54/data/dataset.urls) to download all data sets approx 2.9Gb.

**Comment by sverhoeven** [comment]
Also to PR #104 a [CI job](https://github.com/ESMValGroup/ESMValTool_Tutorial/runs/940559097?check_suite_focus=true) was added to run the example recipe.
