### ISSUE TITLE
readme.md file

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValTool_Tutorial#57]
We'll need to work on the Readme file too. 

However, this file isn't really that useful. It's just the cover page for the tutorial gitpage.

It should include:
- first and foremost, a link to the tutorial page. 
- link to instructions for tutors
- link to contributing
- link to code of conduct
- list of authors
- link to citation.
- licence info

**Comment by BenMGeo** [comment]
Maybe also add a rough estimate of time needed for preparation (Installation plus working through the tutorial).
