### ISSUE TITLE
Move "how to cite" to its own page in the extras directory

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValTool_Tutorial#58]
"**How to cite**" has appeared in 
the[ readme](https://github.com/ESMValGroup/ESMValTool_Tutorial#citation), 
[Index](https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/index.md#how-to-cite-esmvaltool),
[introduction](https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/_episodes/01-introduction.md#what-is-esmvaltool), last line in the section what is esmvaltool.
[episode7-conclusion](https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/_episodes/07-conclusions.md#how-do-i-cite-esmvaltool) 
and[ about page](https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/_extras/about.md#citation). 

It appears too many places. We should just add it in an extras page, and link to it in those other places.

**Comment by JaroCamphuijsen** [comment]
@ledm I agree and it should be updated once we have a release
