### ISSUE TITLE
Tutorial sprint 02

### ISSUE THREAD

**Issue by SarahAlidoost** [ESMValGroup/ESMValTool_Tutorial#63]
@ledm, @BenMGeo, @rswamina, @hb326, @LisaBock, @Peter9192, @bouweandela, @nielsdrost, @valeriolucarini, @JaroCamphuijsen 

Hi all, 

As discussed in the esmvaltool monthly meeting, we will plan a **one-day** meeting to talk about topics related to the tutorial and work on some issues. The meeting covers:

- Work on issues #22 (#45 and #54)  (#47 and #58) #57 #65
- Polishing the lessons and work on issues #53  #59 #62 #64 
- Make action plans for testing 
- Complete the outlines for advanced-parts of the tutorial
- Discuss dissemination

If you want to discuss other topics that are not listed above, please mention them in this issue. 

We kindly invite you to join the meeting. To decide the date, please participate in the doodle poll the link below by **Next Monday 13th July**. Thank you.
https://doodle.com/poll/fprm28ux4xah4eww

**Comment by Peter9192** [comment]
I'll be on holiday, but I did merge #29. Ben created a new issue (#64) for the remaining work on episode 4.

**Comment by ledm** [comment]
Thanks, this was a productive day! All the best!

**Comment by SarahAlidoost** [comment]
For organizing the test, I will contact @hb326 and @LisaBock by email.
