### ISSUE TITLE
Leftover issues for Episode 4

### ISSUE THREAD

**Issue by BenMGeo** [ESMValGroup/ESMValTool_Tutorial#64]
(Following #29, #34)
The left over issues of the recipe tutorial lesson "episode 4" are the following: 

- [x] including links if the episode order and files are fixed (@BenMGeo)
- [ ] reviewing the whole tutorial to suggest the same editors (vim vs nano vs ....) as @hb326 mentioned --> is part of the polishing of the whole tutorial
- [x] the remark on the FX files errors might be reviewed by @ledm to make sure the neted suggestion is fine (I personally never had any issues here).

**Comment by LisaBock** [comment]
>     * the remark on the FX files errors might be reviewed by @ledm to make sure the neted suggestion is fine (I personally never had any issues here).

@ledm Could you check this issue? We are not sure what is meant by this?

**Comment by LisaBock** [comment]
> 
> 
> > ```
> > * the remark on the FX files errors might be reviewed by @ledm to make sure the neted suggestion is fine (I personally never had any issues here).
> > ```
> 
> @ledm Could you check this issue? We are not sure what is meant by this?

So,  I tested it and it works fine.

**Comment by SarahAlidoost** [comment]
Issue https://github.com/ESMValGroup/ESMValTool_Tutorial/issues/77 is made for text editors
