### ISSUE TITLE
Add contact email address

### ISSUE THREAD

**Issue by JaroCamphuijsen** [ESMValGroup/ESMValTool_Tutorial#68]
There are several places where we want users of the lesson to be able to contact the tutorial development team. I suppose this should be the ESMValTool user engagement team. Does this team already have a specialized email address or one specified contact person of which we could add the email address?

Places to add the email address:

_config.yml:33
CONTRIBUTING.md:164
index.md:65 (this line now specifies the esmvaltool mailinglist, but this might not be the best place to point users of this tutorial)

**Comment by SarahAlidoost** [comment]
A link to the contact information is given in the readme, section [Maintainers](https://github.com/ESMValGroup/ESMValTool_Tutorial#maintainers) .
