### ISSUE TITLE
Discussion on the tutorial structure

### ISSUE THREAD

**Issue by ledm** [ESMValGroup/ESMValTool_Tutorial#7]
The initial tutorial structure is:

- introduction
- installation
- configuration
- toy-example
- working-with-recipes
- creating-a-diagnostic-script
- contributing-to-esmvaltool

Are we happy with that structure?

If the tutorial is going to use github pages or a virtual box, then perhaps we could move the installation section later? It would be nice to get into doing science as early as possible.

**Comment by bouweandela** [comment]
@SarahAlidoost @JaroCamphuijsen Any opinion on this, since you know more about the carpentry format and started this tutorial?

**Comment by ledm** [comment]
If it were up to me, I'd try to add more into the introduction. Is it possible to add a quiz or multiple choice questions or something?

**Comment by ledm** [comment]
Note that I've started filling out the tutorial pages in this branch: https://github.com/ESMValGroup/tutorial/tree/development_populating_lessons

**Comment by SarahAlidoost** [comment]
@ledm Thanks for your comment. The first idea was to develop an introductory lesson for a researcher who wants to use esmvaltool to do research on climate data. In principle, this initial structure is based on a concept map that concerns both material and links between them to teach the researcher. I understand your point and think that we can move the “installation” later without losing the links between episodes. Let's ask @JaroCamphuijsen opinion.

**Comment by Peter9192** [comment]
@ledm I think this issue is outdated, right? We discussed the structure in our shared document made a first implementation.
