### ISSUE TITLE
Adding sample config files for different servers

### ISSUE THREAD

**Issue by rswamina** [ESMValGroup/ESMValTool_Tutorial#73]
It might be a good idea to add a couple of sample config-user.yml files to extras or some such directory with each file suited to a specific server such as JASMIN or DLR's. We should probably discuss this during the Lesson Polishing stage.

**Comment by rswamina** [comment]
Another option is to provide the full paths for different servers either in the setup.md file or in the config episode. This is just intended to save time for a new user when starting to personalize the config file.

**Comment by SarahAlidoost** [comment]
The settings are in both [config-user.yml](https://github.com/ESMValGroup/ESMValCore/blob/d924018813f19d13afd68796e4a79e0f2543b5a6/esmvalcore/config-user.yml#L51-L110) and site examples are mentioned in episode 03-configuration.
