### ISSUE TITLE
Use the same text editors in episodes

### ISSUE THREAD

**Issue by SarahAlidoost** [ESMValGroup/ESMValTool_Tutorial#77]
Lessons episodes **04, 03 and 06** should use the same editor vim or nano. And in **episode 02**, in the section [install julia](https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/_episodes/02-installation.md#install-julia), where it says: Open the file in your favorite editor, should be changed to one of the text editors.

**Comment by bouweandela** [comment]
I would recommend nano, it's much simpler than vi.
