### ISSUE TITLE
Fix citation information on title page

### ISSUE THREAD

**Issue by JaroCamphuijsen** [ESMValGroup/ESMValTool_Tutorial#79]
The current citation information on the [title page](https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/index.md) line 81 - 97 requires some reviewing and consideration:

- There is a cite link all the way down in the footer which points to the [CITATION](https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/CITATION) file where the exact same information resides as in this section in the title page. So it might be favorable to just delete this part.
- If we decide to leave it here explicitly, the location is maybe a bit odd and it might be too elaborate, we can also just refer to the documentation if there is information on how to cite ESMValTool (which should be there as well) or link again to the CITATION file. 
- The paper that is now under "Please cite esmvaltool as:" might be changed to either the [technical paper](https://gmd.copernicus.org/articles/13/1179/2020/) or the [older diagnostics paper](https://gmd.copernicus.org/preprints/gmd-2019-291/) that includes more institutes and authors. I think preference is the technical paper as that is really about the tool including the full core development team, and not necessarily about the diagnostics which will grow and change more over time.

**Comment by bouweandela** [comment]
It would be good provide the same information/link to https://docs.esmvaltool.org/en/latest/introduction.html#license

**Comment by SarahAlidoost** [comment]
Another related issue is #58. The citation should be mentioned once and in the CITATION file.
