### ISSUE TITLE
Broken link and typo in setup.md

### ISSUE THREAD

**Issue by SarahAlidoost** [ESMValGroup/ESMValTool_Tutorial#80]
In the last section of setup page ([Install conda](https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/setup.md#install-conda)) the link to **installation episode** is broken. 
see the last line:
`More details on this process are available in the Installation episode.`

**Comment by SarahAlidoost** [comment]
there is typo: 
- In the last line of [this section](https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/setup.md#access-to-cmip-and-observational-data-and-a-suitable-compute-cluster): If **neccesairy,** data can be downloaded using....
- in the second line of [this section](https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/setup.md#your-own-machine): ... of space available to install conda & **ESMVAlTool**, but ...

The words **neccesairy,** and **ESMVAlTool** should be fixed.

**Comment by SarahAlidoost** [comment]
In the section [other computing systems](https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/setup.md#other-computing-systems) , replace "FIXME" with a better explanation.

**Comment by lopeztarifa** [comment]
I am currently working on this issue.
