### ISSUE TITLE
Exclude Julia installation

### ISSUE THREAD

**Issue by sverhoeven** [ESMValGroup/ESMValTool_Tutorial#90]
The installation chapter requires you to install Julia which feels cumbersome. With the new `esmvaltool-*` language based packages we could skip installing `esmvaltool-julia`. This would make the installation easier and faster to execute. Depending on the rest of the tutorial we could just install `esmvaltool-python` or if later tutorial chapters require R and ncl install `esmvaltool-python esmvaltool-r esmvaltool-ncl`.

**Comment by JaroCamphuijsen** [comment]
Also currently the Julia installation instructions are only written out for linux, while conda installation instructions are written out for linux and mac (and with a note for windows). This is inconsistent.
