### ISSUE TITLE
Exercise solution on installation chapter is wrong.

### ISSUE THREAD

**Issue by sverhoeven** [ESMValGroup/ESMValTool_Tutorial#92]
The exercise on https://esmvalgroup.github.io/ESMValTool_Tutorial/02-installation/index.html has solution to run `esmvaltool version`, but it should be `esmvaltool --version`. Also the shown output is outdated and does not show the actual version of esmvaltool, but the esmvalcore version.

**Comment by JaroCamphuijsen** [comment]
The exercise is actually up to date with the new CLI of esmvaltool where `esmvaltool version` is the right command
